INSERT INTO users (name, age) VALUES ('Dante', 35);
INSERT INTO users (name, age) VALUES ('Vergil', 35);
INSERT INTO users (name, age) VALUES ('Nero', 18);
INSERT INTO users (name, age) VALUES ('Akuma', 100);
INSERT INTO users (name, age) VALUES ('Ryu', 65);
INSERT INTO users (name, age) VALUES ('Goku', 50);
INSERT INTO users (name, age) VALUES ('Vegeta', 50);
INSERT INTO users (name, age) VALUES ('Naruto', 35);
INSERT INTO users (name, age) VALUES ('Sasuke', 35);
INSERT INTO users (name, age) VALUES ('Luffy', 25);
INSERT INTO users (name, age) VALUES ('Gon', 15);
INSERT INTO users (name, age) VALUES ('Killua', 15);
INSERT INTO users (name, age) VALUES ('Raiden', 40);
INSERT INTO users (name, age) VALUES ('Snake', 55);
INSERT INTO users (name, age) VALUES ('Setsuna', 25);
INSERT INTO users (name, age) VALUES ('Ryuk', 1000);
INSERT INTO users (name, age) VALUES ('Light', 21);
INSERT INTO users (name, age) VALUES ('Mika', 20);
INSERT INTO users (name, age) VALUES ('Orga', 22);
INSERT INTO users (name, age) VALUES ('James', 25);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('DMC', 'Game', 1000, 'May 1st', 'May 15th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('DMC2', 'Game', 2000, 'May 15th', 'May 30th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Naruto', 'TV', 5000, 'June 32nd', 'July 15th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Street Fighter', 'Game', 700, 'July 4th', 'September 12th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Hunter X Hunter', 'TV', 8000, 'December 1st', 'January 9th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Death Note', 'TV', 1000, 'December 21st', 'February 11th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Gundam IBO', 'TV', 6500, 'March 1st', 'October 11th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('One Piece', 'Game', 8000, 'May 17th', 'September 23rd');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('MGS', 'Game', 9000, 'April 5th', 'June 4th');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('DBZ', 'TV', 10000, 'November 11th', 'Jun 5th');

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 3, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 2, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 15, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 5, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (400, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 2, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 12, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 11, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 4, 4);
